# Generated by Django 5.2.5 on 2025-08-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='item',
        ),
        migrations.AddField(
            model_name='airequest',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='material_type',
            field=models.CharField(choices=[('jira', 'Jira'), ('slack', 'Slack'), ('github', 'Github'), ('gmail', 'Gmail')], max_length=20),
        ),
    ]
