# Generated by Django 5.2.5 on 2025-08-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_item_summary_remove_summary_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='raw_data_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
