# Generated by Django 5.2.5 on 2025-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_raw_data_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='raw_data_created_at',
            new_name='origin_data_updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='origin_data_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
