# Generated by Django 5.2.5 on 2025-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_raw_data_created_at_item_origin_data_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
